UBC-MDS/DSCI-532_2025_29_e-commerce-dashboard

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE.md
- README.md
- environment.yml
- reports/m1_proposal.md
- src/app.py
Created base file and structure for the repo as per Milestone 1.
> Initial creation of repo base structure and files

- reports/m1_proposal.md
I have added an example persona of a user of our app. I have also described a possible usage scenario on how that user might use the dashboard we are creating.
> Modified the Proposal to include research question and usage scenario

- README.md
- environment.yml
- src/app.py
I've added a basic Dash app as our MVP for Milestone 1. I've also updated the README for instructions on how to run it. Can you guys give it a try?
> Added basic dash app as MVP and updated environment and readme

- reports/m1_proposal.md
I added section 2 (description of data) for proposal.
> added section 2 for proposal

- src/app.py
- Formed a layout as per the sketch.
- Created placeholder variables to fill in.
> Initial App Layout

- src/app.py
I added filters on dashboard:
- slider for month
- toggle for applied promotions or not
- radio button for fulfillment type
- checkbox for order status
> Add filters on dashboard

- src/app.py
Various code changes and improvements to the filter widgets and logic: -
- Directly load the data from zip file instead of unzipping first
- Fewer status values displayed, grouped by theme
- Added is_promotion field to make the "Promotion" filter functional
- Using DataFrame.query to allow dynamic generation and application of the query logic
- Changed the summary cards to dynamically compute "last month" and "month before last month" summaries, instead of hard coded 2022-06 and 2022-05
> Improvements to filter

- README.md
- [added a hook, badge, and a short welcome message](https://github.com/UBC-MDS/DSCI-532_2025_29_e-commerce-dashboard/commit/63d4d651117b722efcd03ea8187e2cf490a34cc1)
- [added sections for motivation and purpose](https://github.com/UBC-MDS/DSCI-532_2025_29_e-commerce-dashboard/commit/0c509e37cf049b13707e8b899d9ed91914007c79)
- [added installation instructions and section for contributing and support](https://github.com/UBC-MDS/DSCI-532_2025_29_e-commerce-dashboard/commit/8ab143d388d501647a28861b819f05142364b787)
This PR addresses and should close #47 and also close #54 (feedback from Milestone 1)
> Documentation: Improved README.md

- environment.yml
- requirements.txt
- src/app.py
- Created a footer that includes information like - title, short description, group number and group members
- It also includes the date of last updated
- used `gitpython` package to fetch the date of the latest commit and dynamically update the footer.
- added `gitpython` in `environment.yml` and `requirements.txt`
This PR closes #56
> Add footer information

- LICENSE.md
- README.md
- Added creative-commons license for reports
- Updated `README.md` file to address this
This PR should close #48 and also close #59
> Add Creative Commons license for project reports

- src/app.py
- src/callbacks.py
- src/components.py
- src/data.py
- Refactor code from `app.py` into `callbacks.py`, `components.py` and `data.py`
- Made paths relative for deployment on render.com
- Per lecture 6 notes, use `python -m src.app` to run the app from the root folder
> Refactor functions

- .gitignore
- src/app.py
Added space for another visualization, as discussed during lab
> Changed layout to 2x2 including new state sales summary

- src/app.py
- src/callbacks.py
- src/components.py
Now all three summary metrics could update with all filters.
> update: metrics updated with all filters

- src/app.py
- src/callbacks.py
- src/components.py
* update: metrics updated with all filters
* feat: added color indicator and arrow for comparison
update: add space before label text for checkbox
* switched color indicator
* remove +\- signs
> update: metrics updated with all filters (#82)

- README.md
Change from python src/app.py to python -m src.app
> chore:update readme for how to run the dash app as a module

- src/callbacks.py
- src/components.py
- Addresses Issue #94 
closes #94
> fix: use indian numbering system instead of international

- reports/m3-reflection.md
Created the reflection document for Milestone 3
> Create M3 Reflection

- environment.yml
- requirements.txt
- src/app.py
- src/callbacks.py
- src/data.py
- Per Milestone 4, replaced all `.apply()` calls with vectorized operations such as `.map()`. There's still 1 instance of apply being used for Rupee formatting. I plan to have a different solution for that. 
- Resolves #106 
- Made top margin of charts smaller
> Vectorization and caching

- src/app.py
- src/callbacks.py
- src/components.py
- Added support for selecting ranges for both monthly and weekly filters, ensuring that summary metrics update dynamically based on all applied filters.
- Improved chart behavior: Displays explanatory text instead of empty charts when data is missing.
- Updated "Compare to past month" to display the compound growth rate, providing a more accurate representation of trends.
- Removed "Filters" heading from the sidebar and renamed slider titles for better clarity.
- Moved the title to the left, aligning it with the filters for a more cohesive layout.
- Applied a theme to the filters to enhance visual consistency.
- Reduced margins for charts and adjusted summary metrics size to optimize space usage.
Fixed issues: 
- #98 
-  #116 
- #117 
- #112
> Refine Dashboard: Layout, Filters, and Growth Rate Calculation

- src/callbacks.py
- src/components.py
- Resolves #109 
- Changed tooltip to display full amount in Indian rupees
> Added hover for map and tooltip shows full amount
